// Generates src/generated/embedded.mts — the report templates (config.json +
// pull/*.xml) and the sql.js WebAssembly binary, inlined as JS constants.
//
// Why: when the server is compiled into a single Bun executable there is no
// filesystem next to the binary and no node_modules, so anything read via
// fs.readFileSync(__dirname/..) or sql.js's locateFile() fails. Inlining these
// as string constants makes them part of the JS bundle, so the same code path
// works identically under plain `node` and inside the compiled binary.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const codeDir = path.join(here, '..'); // code/
const pullDir = path.join(codeDir, 'pull');
const outDir = path.join(codeDir, 'src', 'generated');
const wasmPath = path.join(codeDir, 'node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');

// 1) report config
const pullConfig = JSON.parse(fs.readFileSync(path.join(pullDir, 'config.json'), 'utf-8'));

// 2) every pull/*.xml template, keyed by basename (== report name)
const pullTemplates = {};
for (const file of fs.readdirSync(pullDir)) {
  if (file.endsWith('.xml')) {
    pullTemplates[file.slice(0, -4)] = fs.readFileSync(path.join(pullDir, file), 'utf-8');
  }
}

// 3) sql.js wasm as base64
const wasmB64 = fs.readFileSync(wasmPath).toString('base64');

fs.mkdirSync(outDir, { recursive: true });
const out = `// AUTO-GENERATED by scripts/build-embeds.mjs — DO NOT EDIT.
// Regenerate with: npm run build:embeds
// Inlines report templates + the sql.js wasm so the server works both under
// node and inside a single compiled (Bun) binary with no filesystem access.

export const pullConfig: { reports: unknown[]; [key: string]: unknown } = ${JSON.stringify(pullConfig)};

export const pullTemplates: Record<string, string> = ${JSON.stringify(pullTemplates)};

export const sqljsWasmBase64: string = ${JSON.stringify(wasmB64)};
`;

const outFile = path.join(outDir, 'embedded.mts');
fs.writeFileSync(outFile, out);
const kb = (n) => (n / 1024).toFixed(0);
console.log(
  `embedded.mts written: ${Object.keys(pullTemplates).length} templates, ` +
    `wasm ${kb(Buffer.byteLength(wasmB64))}KB (b64), total ${kb(Buffer.byteLength(out))}KB`,
);
